# More info:
# - https://docs.astral.sh/uv/guides/integration/github/
# - https://github.com/astral-sh/setup-uv

name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.12"
      - name: Install Python
        run: uv python install
      - name: Build package
        run: uv build
      - name: Publish
        run: uv publish --token ${{ secrets.PYPI_API_TOKEN }}
